modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="armor_trims"
version="1.1"
displayName="Armor Trims Forge"
credits="Made by: Marwinekk"
displayURL="https://www.curseforge.com/members/marwinekk256/projects"
authors="Marwinekk"

[[dependencies.armor_trims]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




